name: Opensource Demo OrangeHRM Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests (e.g. dev, qa, staging)"
        required: true
        default: "qa"

jobs:
  login-test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-playwright
      - name: Run Playwright tests (@login)
        run: ENV=$ENV npx playwright test --grep @login --project=chromium --reporter=list,html,allure-playwright
      - name: Upload reports (HTML + Allure)
        if: always()
        uses: ./.github/actions/upload-reports
        with:
          html_path: playwright-report/
          allure_results_path: allure-results
          allure_output_path: allure-report
          tag: login

  admin-search-test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-playwright
      - name: Run Playwright tests (@admin)
        run: ENV=$ENV npx playwright test --grep @admin --project=chromium --reporter=list,html,allure-playwright
      - name: Upload reports (HTML + Allure)
        if: always()
        uses: ./.github/actions/upload-reports
        with:
          html_path: playwright-report/
          allure_results_path: allure-results
          allure_output_path: allure-report
          tag: admin
