name: Opensource Demo OrangeHRM Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests (e.g. dev, qa)"
        required: true
        default: "qa"
      browser:
        description: "Browser to run tests (chromium, firefox, webkit)"
        required: true
        default: "chromium"
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  login-test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      BROWSER: ${{ github.event.inputs.browser }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-playwright
      - name: Run Playwright tests for login
        run: ENV=$ENV npm run test --grep @login --project=$BROWSER
      - name: Upload reports (HTML + Allure)
        if: always()
        uses: ./.github/actions/upload-reports
        with:
          html_path: playwright-report/
          allure_results_path: allure-results
          allure_output_path: allure-report
          tag: login

  admin-search-test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      BROWSER: ${{ github.event.inputs.browser }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-playwright
      - name: Run Playwright tests for admin search
        run: ENV=$ENV npm run test --grep @login --project=$BROWSER
      - name: Upload reports (HTML + Allure)
        if: always()
        uses: ./.github/actions/upload-reports
        with:
          html_path: playwright-report/
          allure_results_path: allure-results
          allure_output_path: allure-report
          tag: admin
